import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:sun_gate_app/features/home/data/models/category_item_model.dart';
import 'package:sun_gate_app/features/home/data/models/product_model.dart';
import 'package:sun_gate_app/features/marketplace/data/models/company_model.dart';

class HomeState {
  final bool isLoading;
  final List<CategoryItemModel> categories;
 // final List<ProductModel> products;
  final List<CompanyModel> companies;

  const HomeState({
    this.isLoading = false,
    this.categories = const [],
    this.companies = const [],
  //  this.products = const [],
  });

  HomeState copyWith({
    bool? isLoading,
    List<CategoryItemModel>? categories,
    List<CompanyModel>? companies,
 //   List<ProductModel>? products,
  }) {
    return HomeState(
      isLoading: isLoading ?? this.isLoading,
      categories: categories ?? this.categories,
      companies: companies ?? this.companies,
 //     products: products ?? this.products,
    );
  }
}

final homeControllerProvider = Provider<HomeState>((ref) {
  final categories = [
    CategoryItemModel(
      id: '1',
      titleKey: 'categoryBatteries',
      imagePath: 'assets/images/battery.jpg',
    ),
    CategoryItemModel(
      id: '2',
      titleKey: 'categoryInverters',
      imagePath: 'assets/images/inverter.jpg',
    ),
    CategoryItemModel(
      id: '3',
      titleKey: 'categoryPanels',
      imagePath: 'assets/images/panels.jpg',
    ),
    CategoryItemModel(
      id: '4',
      titleKey: 'categorySuppliers',
      imagePath: 'assets/images/suppliers.jpg',
    ),
  ];
  // final companies = [
  //   CompanyModel(
  //     id: '1',
  //     nameKey: 'companyLuminanceName',
  //     coverImagePath: 'assets/images/company_luminance.jpeg',
  //     logoPath: 'assets/images/companies/logo_luminance.png',
  //     shortDescriptionKey: 'companyLuminanceShortDescription',
  //     descriptionKey: 'companyLuminanceDescription',
  //     locationKey: 'companyLuminanceLocation',
  //     rating: 4.7,
  //     reviewCount: 31,
  //     tagKeys: ['categoryBatteries', 'categoryPanels'],
  //   ),
  //   CompanyModel(
  //     id: '2',
  //     nameKey: 'companyVoltGuardName',
  //     coverImagePath: 'assets/images/company_voltguard.jpeg',
  //     logoPath: 'assets/images/companies/logo_voltguard.png',
  //     shortDescriptionKey: 'companyVoltGuardShortDescription',
  //     descriptionKey: 'companyVoltGuardDescription',
  //     locationKey: 'companyVoltGuardLocation',
  //     rating: 4.5,
  //     reviewCount: 24,
  //     tagKeys: ['categoryBatteries', 'categoryInverters'],
  //   ),
  //   CompanyModel(
  //     id: '3',
  //     nameKey: 'companyEcoVoltName',
  //     coverImagePath: 'assets/images/company_ecovolt.jpeg',
  //     logoPath: 'assets/images/companies/logo_ecovolt.png',
  //     shortDescriptionKey: 'companyEcoVoltShortDescription',
  //     descriptionKey: 'companyEcoVoltDescription',
  //     locationKey: 'companyEcoVoltLocation',
  //     rating: 4.6,
  //     reviewCount: 28,
  //     tagKeys: ['categoryPanels', 'categorySuppliers'],
  //   ),
  //   CompanyModel(
  //     id: '4',
  //     nameKey: 'companyZenithName',
  //     coverImagePath: 'assets/images/company_zenith.jpeg',
  //     logoPath: 'assets/images/companies/logo_zenith.png',
  //     shortDescriptionKey: 'companyZenithShortDescription',
  //     descriptionKey: 'companyZenithDescription',
  //     locationKey: 'companyZenithLocation',
  //     rating: 4.8,
  //     reviewCount: 19,
  //     tagKeys: ['categoryBatteries', 'categorySuppliers'],
  //   ),
  //   CompanyModel(
  //     id: '5',
  //     nameKey: 'companySunCoreName',
  //     coverImagePath: 'assets/images/company_suncore.jpeg',
  //     logoPath: 'assets/images/companies/logo_suncore.png',
  //     shortDescriptionKey: 'companySunCoreShortDescription',
  //     descriptionKey: 'companySunCoreDescription',
  //     locationKey: 'companySunCoreLocation',
  //     rating: 4.4,
  //     reviewCount: 16,
  //     tagKeys: ['categoryPanels', 'categoryInverters'],
  //   ),
  //   CompanyModel(
  //     id: '6',
  //     nameKey: 'companyNovaGridName',
  //     coverImagePath: 'assets/images/company_novagrid.jpg',
  //     logoPath: 'assets/images/logo_novagrid.png',
  //     shortDescriptionKey: 'companyNovaGridShortDescription',
  //     descriptionKey: 'companyNovaGridDescription',
  //     locationKey: 'companyNovaGridLocation',
  //     rating: 4.6,
  //     reviewCount: 22,
  //     tagKeys: ['categorySuppliers', 'categoryPanels'],
  //   ),
  // ];
  // const products = [
  //   ProductModel(
  //     id: 'p1',
  //     companyId: '1',
  //     nameKey: 'productP1Name',
  //     imagePath: 'assets/images/products/p1.jpg',
  //     descriptionKey: 'productP1Description',
  //     howItWorksKeys: ['productP1How1', 'productP1How2', 'productP1How3'],
  //     price: 120,
  //     ownerNameKey: 'ownerAhmadSaleh',
  //     ownerRoleKey: 'roleLuminanceEngineer',
  //     ownerPhone: '+972 598 111 111',
  //     ownerEmail: 'luminance@sungate.com',
  //     tagKeys: ['categoryPanels'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p2',
  //     companyId: '1',
  //     nameKey: 'productP2Name',
  //     imagePath: 'assets/images/products/p2.jpg',
  //     descriptionKey: 'productP2Description',
  //     howItWorksKeys: ['productP2How1', 'productP2How2', 'productP2How3'],
  //     price: 250,
  //     ownerNameKey: 'ownerAhmadSaleh',
  //     ownerRoleKey: 'roleLuminanceEngineer',
  //     ownerPhone: '+972 598 111 111',
  //     ownerEmail: 'luminance@sungate.com',
  //     tagKeys: ['categoryBatteries'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p3',
  //     companyId: '2',
  //     nameKey: 'productP3Name',
  //     imagePath: 'assets/images/products/p3.jpg',
  //     descriptionKey: 'productP3Description',
  //     howItWorksKeys: ['productP3How1', 'productP3How2', 'productP3How3'],
  //     price: 85,
  //     ownerNameKey: 'ownerMohamoudAli',
  //     ownerRoleKey: 'roleSunGridManager',
  //     ownerPhone: '+972 599 000 000',
  //     ownerEmail: 'owner@sungate.com',
  //     tagKeys: ['categoryInverters'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p4',
  //     companyId: '2',
  //     nameKey: 'productP4Name',
  //     imagePath: 'assets/images/products/p4.jpg',
  //     descriptionKey: 'productP4Description',
  //     howItWorksKeys: ['productP4How1', 'productP4How2', 'productP4How3'],
  //     price: 310,
  //     ownerNameKey: 'ownerMohamoudAli',
  //     ownerRoleKey: 'roleSunGridManager',
  //     ownerPhone: '+972 599 000 000',
  //     ownerEmail: 'owner@sungate.com',
  //     tagKeys: ['categoryBatteries'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p5',
  //     companyId: '3',
  //     nameKey: 'productP5Name',
  //     imagePath: 'assets/images/products/inver.jpg',
  //     descriptionKey: 'productP5Description',
  //     howItWorksKeys: ['productP5How1', 'productP5How2', 'productP5How3'],
  //     price: 300,
  //     ownerNameKey: 'ownerOmarKhaled',
  //     ownerRoleKey: 'roleEcoVoltManager',
  //     ownerPhone: '+972 597 222 222',
  //     ownerEmail: 'ecovolt@sungate.com',
  //     tagKeys: ['categoryInverters'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p6',
  //     companyId: '3',
  //     nameKey: 'productP6Name',
  //     imagePath: 'assets/images/products/p6.png',
  //     descriptionKey: 'productP6Description',
  //     howItWorksKeys: ['productP6How1', 'productP6How2', 'productP6How3'],
  //     price: 180,
  //     ownerNameKey: 'ownerOmarKhaled',
  //     ownerRoleKey: 'roleEcoVoltManager',
  //     ownerPhone: '+972 597 222 222',
  //     ownerEmail: 'ecovolt@sungate.com',
  //     tagKeys: ['categoryPanels'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p7',
  //     companyId: '4',
  //     nameKey: 'productP7Name',
  //     imagePath: 'assets/images/products/battery2.jpg',
  //     descriptionKey: 'productP7Description',
  //     howItWorksKeys: ['productP7How1', 'productP7How2', 'productP7How3'],
  //     price: 450,
  //     ownerNameKey: 'ownerSaraNabil',
  //     ownerRoleKey: 'roleZenithSpecialist',
  //     ownerPhone: '+972 596 333 333',
  //     ownerEmail: 'zenith@sungate.com',
  //     tagKeys: ['categoryBatteries'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p8',
  //     companyId: '4',
  //     nameKey: 'productP8Name',
  //     imagePath: 'assets/images/products/p8.jpg',
  //     descriptionKey: 'productP8Description',
  //     howItWorksKeys: ['productP8How1', 'productP8How2', 'productP8How3'],
  //     price: 390,
  //     ownerNameKey: 'ownerSaraNabil',
  //     ownerRoleKey: 'roleZenithSpecialist',
  //     ownerPhone: '+972 596 333 333',
  //     ownerEmail: 'zenith@sungate.com',
  //     tagKeys: ['categoryBatteries'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p9',
  //     companyId: '5',
  //     nameKey: 'productP9Name',
  //     imagePath: 'assets/images/products/p9.png',
  //     descriptionKey: 'productP9Description',
  //     howItWorksKeys: ['productP9How1', 'productP9How2', 'productP9How3'],
  //     price: 90,
  //     ownerNameKey: 'ownerAliHasan',
  //     ownerRoleKey: 'roleSunCoreSupervisor',
  //     ownerPhone: '+972 595 444 444',
  //     ownerEmail: 'suncore@sungate.com',
  //     tagKeys: ['categoryPanels'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p10',
  //     companyId: '5',
  //     nameKey: 'productP10Name',
  //     imagePath: 'assets/images/products/p10.png',
  //     descriptionKey: 'productP10Description',
  //     howItWorksKeys: ['productP10How1', 'productP10How2', 'productP10How3'],
  //     price: 70,
  //     ownerNameKey: 'ownerAliHasan',
  //     ownerRoleKey: 'roleSunCoreSupervisor',
  //     ownerPhone: '+972 595 444 444',
  //     ownerEmail: 'suncore@sungate.com',
  //     tagKeys: ['categoryPanels'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p11',
  //     companyId: '6',
  //     nameKey: 'productP11Name',
  //     imagePath: 'assets/images/products/p11.png',
  //     descriptionKey: 'productP11Description',
  //     howItWorksKeys: ['productP11How1', 'productP11How2', 'productP11How3'],
  //     price: 520,
  //     ownerNameKey: 'ownerRamiAdel',
  //     ownerRoleKey: 'roleNovaGridEngineer',
  //     ownerPhone: '+972 594 555 555',
  //     ownerEmail: 'novagrid@sungate.com',
  //     tagKeys: ['categorySuppliers'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  //   ProductModel(
  //     id: 'p12',
  //     companyId: '6',
  //     nameKey: 'productP12Name',
  //     imagePath: 'assets/images/products/p12.png',
  //     descriptionKey: 'productP12Description',
  //     howItWorksKeys: ['productP12How1', 'productP12How2', 'productP12How3'],
  //     price: 610,
  //     ownerNameKey: 'ownerRamiAdel',
  //     ownerRoleKey: 'roleNovaGridEngineer',
  //     ownerPhone: '+972 594 555 555',
  //     ownerEmail: 'novagrid@sungate.com',
  //     tagKeys: ['categorySuppliers'],
  //     imageProfile: 'assets/images/profile.jpg',
  //   ),
  // ];
  return HomeState(
    categories: categories,
    //   companies: companies,
  //  products: products,
  );
});
